<?php
use Core\Auth;
use Core\Session;
$logged=Auth::isLogged();
$selectedItem=Session::get('selectedItem');
$pageTitle=Session::get('pageTitle');
$pageDescription=Session::get('pageDescription');
$pageRobots=Session::get('pageRobots');
$message=$this->flashMessage;
$class=$this->flashClass;
$alertHide="style='display:none'";
if(isset($message)){
    $alertHide='';
}
?>
<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<title><?php echo $pageTitle?></title>
<meta name="description" content="<?php echo $pageDescription?>" />
<meta name="robots" content="<?php echo $pageRobots?>" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="/css/style.css" />
</head>
<body>
	<?php if($logged){?>
    <strong>
        <a href="#"><?php echo Auth::userName()?></a>
        <a href="/logout">
            Logout
            <span class="glyphicon glyphicon-off"></span>
        </a>
    </strong>
    <?php }?>
	<div class="container">
        <div class="content">
            <div id='flashMessage' class='flash-bottom-right alert <?php echo $class?>' <?php echo $alertHide?>><?php echo $message ?></div>
            <?php $this->content();?>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</body>
</html>