<?php
use Core\FlashMessage;
use Core\Session;
use Core\Auth;

$selectedItem=Session::get('selectedItem');
?>
<!doctype html>
<html lang="pt-BR">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
<title></title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="/css/style.css" />
</head>
<body>
	<?php if(Auth::isLogged()){?>
    <strong>
        <a href="#"><?php echo Auth::userName()?></a>
        <a class="logged" href="/login/logout">
            Logout
            <span class="glyphicon glyphicon-off"></span>
        </a>
    </strong>
    <?php }?>
	<div class="container">
        <div class="header">
            <ul class="header-menu">
                <li class="header-menu-item <?php (($selectedItem == 1)?(print "active"):(""))?>">
                    <a href="/home">Home</a>
                </li>
            </ul>
            <div class="dropdown">
                <a href="#" class="header-menu-mobile dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-menu-hamburger"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li>
                        <a href="/">Home</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content">
        <?php FlashMessage::show(); ?>
        <?php $this->content();?>
        </div>
        <div class="footer"></div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</body>
</html>