<?php
use Core\Auth;
use Core\FlashMessage;
$logged=Auth::isLogged();
?>
<!doctype html>
<html lang="pt-BR">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
<title></title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="/css/style.css" />
</head>
<body>
	<?php if($logged){?>
    <strong>
        <a href="#"><?php echo Auth::userName()?></a>
        <a href="/logout">
            Logout
            <span class="glyphicon glyphicon-off"></span>
        </a>
    </strong>
    <?php }?>
	<div class="container">
        <div class="content">
            <?php FlashMessage::show(); ?>
            <?php $this->content();?>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</body>
</html>