<div class="login">
	<form class="form-signin" method="post" action="/login">
		<fieldset>
			<legend>Login</legend>
			<label>Usuário: </label>
			<input type="text" name="userName" placeholder="Usuário" class="form-control" required autofocus />
			<label>Senha: </label>
			<input type="password" name="password" placeholder="Senha" class="form-control" required />
			<br />
			<button type="submit" title="Entrar" class="btn btn-info btn-red form-control">Salvar</button>
		</fieldset>
	</form>
</div>