<?php
$attempts=$this->attempts;
$siteKey='';
$class='';
$callback='';
$onclick='onclick="login();"';
if($attempts>=3){
    $siteKey='data-sitekey=""';
    $class='g-recaptcha';
    $callback='data-callback="submitForm"';
    $onclick='';
}
?>
<div class="container">
<form id="loginForm" class="shadow-lg rounded w-50 mt-5 mx-auto p-5" action="/login" method="post">
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
    <div class="form-group">
        <label>Usuário:</label>
        <input type="text" name='userName' class="form-control" placeholder="Usuário" required autofocus />
    </div>
    <div class="form-group">
        <label>Senha</label>
        <input type="password" name="password" class="form-control" placeholder="Senha" required />
    </div>
    <button <?php echo $siteKey ?> <?php echo $callback?> data-badge="bottomleft" <?php echo $onclick ?> class="btn btn-primary btn-block btn-lg <?php echo $class?>">Entrar</button>
</form>
</div>
<script type="text/javascript">
function login() {
    $('*').css('cursor','wait');
    $('.btn').addClass('link-disabled');
    $("#loginForm").submit();
}
</script>
<?php
$production=false;
$env = getenv('APPLICATION_ENV');
if ($env=='production')$production=true;
if($production){
?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>
function submitForm(token) {
    $('*').css('cursor','wait');
    $('.btn').addClass('link-disabled block');
    document.getElementById("loginForm").submit();
}
</script>
<?php }